name: Build and Publish Multi-Platform Docker Image

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.check-release.outputs.new_release }}
      latest_version: ${{ steps.get-version.outputs.latest_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch latest version from PyPI
        id: get-version
        run: |
          LATEST_VERSION=$(curl -s https://pypi.org/pypi/cyberdrop-dl-patched/json | jq -r '.info.version')
          echo "Latest version: $LATEST_VERSION"
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Check if release is new
        id: check-release
        run: |
          set -e
          DOCKERHUB_IMAGE="ne0lith/cdl-docker"
          LATEST_VERSION=${{ steps.get-version.outputs.latest_version }}

          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${DOCKERHUB_IMAGE}/tags?page_size=100" | jq -r '.results[].name')

          if echo "$TAGS" | grep -q "^${LATEST_VERSION}$"; then
            echo "No new release detected. Latest version $LATEST_VERSION is already on Docker Hub."
            echo "new_release=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "New release detected: $LATEST_VERSION"
            echo "new_release=true" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    needs: check-release
    runs-on: ubuntu-latest
    if: needs.check-release.outputs.new_release == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          DOCKERHUB_IMAGE="ne0lith/cdl-docker"
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/cdl-docker"
          LATEST_VERSION=${{ needs.check-release.outputs.latest_version }}

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg CYBERDROP_DL_VERSION=$LATEST_VERSION \
            --tag $DOCKERHUB_IMAGE:${LATEST_VERSION} \
            --tag $GHCR_IMAGE:${LATEST_VERSION} \
            --push .

      - name: Push latest Docker tag
        run: |
          DOCKERHUB_IMAGE="ne0lith/cdl-docker"
          GHCR_IMAGE="ghcr.io/${{ github.repository_owner }}/cdl-docker"
          LATEST_VERSION=${{ needs.check-release.outputs.latest_version }}

          # Tag and push as 'latest'
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg CYBERDROP_DL_VERSION=$LATEST_VERSION \
            --tag $DOCKERHUB_IMAGE:latest \
            --tag $GHCR_IMAGE:latest \
            --push .

      - name: Notify Discord
        run: |
          DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
          LATEST_VERSION=${{ needs.check-release.outputs.latest_version }}

          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ New Docker image build pushed! Version: $LATEST_VERSION\"}" \
          $DISCORD_WEBHOOK_URL
